.circleci/config.yml, Makefile, README.md
Update badges in README for active integrations
Fixes #(issue)
=> Update Circle badge

deploy/Dockerfile-postgres, deploy/Dockerfile-slim
=> update openssl within retraced images

deploy/Dockerfile-postgres, deploy/Dockerfile-slim
=> update openssl in the correct location within dockerfile-slim

deploy/Dockerfile-postgres, deploy/Dockerfile-slim, package.json, src/models/admin_token/store.ts, src/test/models/admin_token/store_test.ts, yarn.lock
Patching container image CVEs
Fixes #(issue)
=> Patch container images

CODE_OF_CONDUCT.md
Signed-off-by: OGtrilliams <tribecca@tribecc.us>
Added a CoC for potential open source contributors
Fixes #(issue)
=> added code of conduct page for contributors

README.md
=> fix misspellings in readme

.circleci/.anchore/grype.yaml
=> remove ignored apk packages scan (v1.3)

.circleci/.anchore/grype.yaml
=> remove ignored apk packages vulns

Dockerfile.skaffold, kustomize/base/nsqd-deployment.yaml, kustomize/base/processor-deployment.yaml, kustomize/overlays/dev/kustomization.yaml, kustomize/overlays/skaffold/kustomization.yaml, skaffold.yaml, src/_processor/index.ts
=> WIP on support for M1

.gitignore, Makefile, deploy/Dockerfile-slim
=> Bump retraceddb from 4GB to 8GB

Makefile
=> Fix bad bash in Makefile

src/common/helpers.ts, src/handlers/admin/listProjects.ts, src/models/project/list.ts, src/models/project/listall.ts
Added the offset and limit query params using which we can get a paginated list of projects and made the required query changes.
=> Pagination Support for ListProject API

.circleci/config.yml, CODE_OF_CONDUCT.md, kustomize/base/api-deployment.yaml, kustomize/base/cron-deployment.yaml, kustomize/base/dbutil-deployment.yaml, kustomize/base/migratees-job.yaml, kustomize/base/migratepg-job.yaml, kustomize/base/processor-deployment.yaml, kustomize/base/replicated-registry-secret.yaml, kustomize/overlays/dev/api-deployment.yaml, kustomize/overlays/dev/cron-deployment.yaml, kustomize/overlays/dev/integrationtest.yaml, kustomize/overlays/dev/migratees-job.yaml, kustomize/overlays/dev/migratepg-job.yaml, kustomize/overlays/dev/processor-deployment.yaml, kustomize/overlays/skaffold/api-deployment.yaml, kustomize/overlays/skaffold/cron-deployment.yaml, kustomize/overlays/skaffold/dbutil-deployment.yaml, kustomize/overlays/skaffold/integrationtest.yaml, kustomize/overlays/skaffold/migratees-job.yaml, kustomize/overlays/skaffold/migratepg-job.yaml, kustomize/overlays/skaffold/processor-deployment.yaml, package.json, skaffold.yaml
=> switching to docker hub

integration/test/admin/getproject.ts, integration/test/admin/updateApiToken.ts, integration/test/enterprise/search.ts, integration/test/enterprise/searchscope.ts, integration/test/env.ts, integration/test/pkg/adminUser.ts, integration/test/publisher/createevent.ts, integration/test/publisher/createeventbulk.ts, integration/test/publisher/deletetokens.ts, integration/test/publisher/groupnameresolution.ts, integration/test/publisher/listtokens.ts, integration/test/publisher/search.ts, integration/test/viewer/search.ts, package.json
=> Fixed integration tests

package.json, src/_processor/healthz.ts, src/_processor/persistence/redis.ts
Fixes https://github.com/retracedhq/retraced/issues/689
Fixes #(issue)
=> redis streaming should be optional

.github/workflows/main.yml
Using the version from `package.json` tas a tag to the docker image
=> Using package version in actions

.github/ISSUE_TEMPLATE/config.yml, src/_processor/services/Emailer.ts, src/_processor/services/templates/deletionRequest.ts, src/_processor/services/templates/inviteToTeam.ts, src/_processor/services/templates/reportDay.ts, src/controllers/AdminController.ts, src/controllers/EnterpriseController.ts, src/controllers/PublisherController.ts, src/handlers/createEvent.ts, src/handlers/graphql/index.ts, src/swagger.ts
=> updated urls

src/_processor/index.ts
=> Initialise geo data fetch if maxmind key is set, load geo nsq worker only if maxmind key is set

.github/workflows/main.yml
The Docker Cyclonedx report was not being uploaded, minor fixes to make it work
=> GitHub action fixes

src/_processor/index.ts, src/controllers/EnterpriseController.ts, src/handlers/createEvent.ts, src/handlers/enterprise/graphql.ts, src/handlers/enterprise/pumpActiveSearch.ts, src/handlers/enterprise/searchAdHoc.ts, src/handlers/viewer/createEitapiToken.ts, src/handlers/viewer/deleteEitapiToken.ts, src/handlers/viewer/graphql.ts, src/handlers/viewer/listEitapiTokens.ts, src/handlers/viewer/searchEvents.ts, src/handlers/viewer/updateEitapiToken.ts
=> Add created time to internal events

src/_db/commands/up/es.ts, src/_db/commands/up/pg.ts, src/_db/common.ts, src/_processor/index.ts, src/error-notifier/bugsnag.ts, src/error-notifier/index.ts, src/index.ts, src/router.ts
Fixes https://github.com/retracedhq/retraced/issues/759
=> Bugsnag.notify is now a no-op if Bugsnag.start hasn't been called

.github/workflows/main.yml
Trigger main workflow on push to `[main, release]` and on `pull_request` ( checkout will happen against merge commit )
=> Switch to pull_request trigger

.circleci/config.yml, README.md, deploy/Dockerfile-postgres
=> Fix postgres image vulnerabilities

deploy/Dockerfile-nsq
=> use /tmp as the working directory, not /home

src/handlers/graphql/search.ts, src/models/event/filter.ts
=> fix for pg search

integration/test/admin/createAdminToken.ts, integration/test/admin/createApiToken.ts, integration/test/admin/createEnvironment.ts, integration/test/admin/createInvite.ts, integration/test/admin/createTemplate.ts, integration/test/admin/deleteApiToken.ts, integration/test/admin/deleteEnvironment.ts, integration/test/admin/deleteInvite.ts, integration/test/admin/deleteTemplate.ts, integration/test/admin/listInvites.ts, integration/test/admin/searchTemplates.ts, integration/test/admin/updateApiToken.ts, integration/test/env.ts, src/_db/commands/reindex/shared/page.ts, src/_processor/workers/normalizeEvent.ts, src/e2e-tests/handlers/enterprise/createActiveSearch.ts, src/models/api_token/index.ts, src/models/deletion_confirmation/index.ts, src/models/deletion_request/index.ts, src/models/invite/index.ts, src/models/invite/list.ts, src/models/user/index.ts, src/security/helpers.ts, src/security/vouchers.ts, src/test/security/helpers.ts
- Fixed parsing of authorization header to cater to all combinations of id, token and admin_token.
- Enabled more integration tests
=> Auth check fix

.github/workflows/main.yml, docker-compose.yaml
- Restructured the GitHub actions steps
- Added steps to run docker-compose with `PG_SEARCH` enabled
- Ran integration tests on both the configurations
=> Integration tests with PG_SEARCH mode

.github/workflows/main.yml
=> Gh actions fix

deploy/Dockerfile-nsq, deploy/Dockerfile-postgres
=> chore: cves

deploy/Dockerfile-slim
=> updated supercronic

src/_processor/common.ts, src/_processor/index.ts, src/_processor/workers/NormalizeRepairer.ts
=> sync geo on startup only if table is empty

src/models/event/query.ts
=> logs cleanup

.circleci/config.yml, .gitignore, Makefile, README.md, deploy/Dockerfile-slim
1. Makefile changes and README updates to help run image scans locally.
1. Added SNYK_TOKEN. Possibly this is a change in snyc scan behavior.
```
> api@1.3.39 snyk-protect /src
> snyk protect
Unauthorized: please ensure you are logged in using `snyk auth`
```
Fixes #(issue)
=> Make and readme updates with info used to make this release

deploy/Dockerfile-slim, package-lock.json, package.json
=> updated node to v18.18.0

package-lock.json, package.json
=> cleaned up prom-client

package-lock.json, package.json
=> cleaned up types for statsd-client

deploy/Dockerfile-slim, kustomize/overlays/demo/services/admin-portal-service.yaml, kustomize/overlays/demo/services/api-service.yaml, package.json
=> turn off http, update ssl security policy, updated node

package-lock.json, package.json
=> updated retraced-js

package-lock.json, package.json, src/models/project/create.ts
=> updated segment lib

src/controllers/EnterpriseController.ts, src/handlers/graphql.ts, src/handlers/graphql/handler.ts, src/test/handlers/graphql.ts
[Reference](https://github.com/retracedhq/retraced/pull/1133)
=> Fix DoS Vulnerability in GraphQL endpoint

deploy/Dockerfile-slim
=> update alpine, supercronic

deploy/Dockerfile-slim
=> node 20.11.1

src/_db/commands/reindex/postgres.ts
Taken from https://github.com/retracedhq/retraced/pull/1295
Fixes #(issue)
=> Missing else when rebuilding index

.circleci/.anchore/grype.yaml, README.md
Removing resolved CVEs from the ignore list
Fixes #(issue)
=> Remove ignored CVEs

deploy/Dockerfile-slim
=> updated node

.github/workflows/main.yml
=> chore: Update artifact upload retention to 1 day

deploy/Dockerfile-slim, package-lock.json
=> updated package-lock

src/_processor/workers/saveEventToElasticsearch.ts
Follow up to https://github.com/retracedhq/retraced/pull/1381 that handles one more location.
Fixes #(issue)
=> Remove invalid date from target.fields

.prettierignore, deploy/Dockerfile-slim, package.json, src/controllers/AdminController.ts, src/controllers/EnterpriseController.ts, src/controllers/PublisherController.ts, swagger.json, tsoa.json
=> added generated swagger file

src/controllers/AdminController.ts, src/e2e-tests/handlers/admin/createTemplate.ts, src/handlers/admin/createTemplate.ts
Bulk support for template creation
Template creation api supports bulk option now, api will accept array for templates or single template object and respond accordingly
=> Bulk template api

src/models/event/filter.ts
Fixes the sql query issue with first and cursor for PG
=> refactor: Update filter function to include additional cursor values

src/models/event/query.ts, src/test/models/event/query.ts
=> refactor: Update sort criteria in searchParams function

integration/test/pkg/specs.ts, integration/test/viewer/searchpaginated.ts
Added integration test cases for Paginated search api
=> feat: Pagination test cases

docker-compose-base.yaml, kustomize/overlays/dbs/postgres.yaml, kustomize/overlays/demo/kustomization.yaml, kustomize/overlays/dev/kustomization.yaml
=> updated versions

.circleci/.anchore/grype.yaml, .circleci/config.yml, deploy/Dockerfile-postgres
=> Add ignored postgresql vulns to grype.yaml and update circleci docker version
